# Generated by Django 4.2.6 on 2023-10-14 15:59

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="address",
            old_name="user",
            new_name="user_id",
        ),
    ]
